### ISSUE TITLE
Porcelain doesn't melt

### ISSUE THREAD

**Issue by AmazTING** [R74nCom/sandboxels#130]
It should melt between 1305 and 1346 degrees celcius

**Comment by aduncan99** [comment]
Are you currently working on fixing this issue? Or I can create a mod for it.

**Comment by N-coder82** [comment]
Porcalin shouln't melt, its a heat-proof substance.

**Comment by aduncan99** [comment]
Technically it does. Look it up.
I'll add a mod anyway because why not.
