### ISSUE TITLE
Things You need to do

### ISSUE THREAD

**Issue by ininja-ininja** [R74nCom/sandboxels#144]
1. Make plant life absorb water.
2. Improve human intelligence. Have you seen the humans in the game Worldbox? The humans in Sandboxels should be like that.
3. Add human elements, [Like SpikeViper's Biology mod for TPT](https://powdertoy.co.uk/Discussions/Thread/View.html?Thread=26571).
4. Water spreads out evenly in the game and in real life after pouring it, but in the game that happens too slowly, try improving that speed.

**Comment by slweeb** [comment]
https://sandboxels.r74n.com/feedback

**Comment by ininja-ininja** [comment]
fine i sent feedback i had to copy and paste it though but it wont have the same formatting
