### ISSUE TITLE
star_wars.js

### ISSUE THREAD

**Issue by SeaPickle754** [R74nCom/sandboxels#158]
I'm sorry for bothering you, but star_wars.js isn't working. Even though the pull request went through (thank you, by the way), it is not showing up in the mod list. I don't know if I need to update that directly. Also, when I just type "star_wars.js" in the mod manager, I get a 404 error in the console. I don't know what I'm doing wrong. Can you please help me fix this problem
**TL; DR**
My mod is not running, and sometimes gives me a 404 error, even though my pull request was merged.

**Comment by slweeb** [comment]
I just responded to the PR -- Hello! It looks like you made a mistake by submitting it to the root directory instead of the mods folder. Please move it and make another pull request! :)

**Comment by SeaPickle754** [comment]
Ok, thank you! Later today, I started suspecting that was it, but I had no way to check it until now. Thank you, and I changed it to a PR. Thanks in advance for your patience!
