### ISSUE TITLE
Why is sandboxels unplayable with this

### ISSUE THREAD

**Issue by Uraniumeate** [R74nCom/sandboxels#307]
I'm playing sandboxels yet. I can't and I can only play if I don't use the mod so please fix this as I want to do more stuff.

**Comment by Uraniumeate** [comment]
This no let me play

**Comment by Uraniumeate** [comment]
Helpppp

**Comment by Uraniumeate** [comment]
I need the owner of this mod to fix ittttt

**Comment by slweeb** [comment]
I don't make mods. Stop spamming. You're not welcome back here.
