### ISSUE TITLE
Cactus should be better

### ISSUE THREAD

**Issue by Angrygodzillaa** [R74nCom/sandboxels#328]
Add cactus sprout and make the cactus better with gradients

**Comment by Angrygodzillaa** [comment]
But for the flowers_and_forests.js

**Comment by HACKERPRO908** [comment]
so list additions and removing items u want
i will decide to put it forwards or not

**Comment by slweeb** [comment]
https://sandboxels.r74n.com/feedback

**Comment by HACKERPRO908** [comment]
@slweeb, @Angrygodzillaa is talking about my mod not the sandboxels base game
