### ISSUE TITLE
Quicksand_one 

### ISSUE THREAD

**Issue by jakob3797** [R74nCom/sandboxels#579]
It doesn’t show that it was Updated in the mods file

**Comment by slweeb** [comment]
what is that supposed to mean..?

**Comment by jakob3797** [comment]
![IMG_0197](https://github.com/R74nCom/sandboxels/assets/167775393/5bf809e6-f9d7-4164-b37e-990607d5ff46)

**Comment by slweeb** [comment]
oh yeah, you made a mistake and put it in the root directory instead of the mods folder.

**Comment by jakob3797** [comment]
Oh ok

**Comment by slweeb** [comment]
fixed it
