### ISSUE TITLE
Can someone test this 

### ISSUE THREAD

**Issue by jakob3797** [R74nCom/sandboxels#598]
`elements.eunstainer_up2 = {
     behavior: behaviors.WALL,
     behaviorOn: [
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
 elements.eunstainer_up1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_down2 = {
     behavior: behaviors.WALL,
     behaviorOn: [
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_down1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left2 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "ST:-1|ST:-1|XX|XX|XX",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "ST:-1|XX|XX",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_right2 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "XX|XX|XX|ST:-1|ST:-1",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_right1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|ST:-1",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
}; `

**Comment by Tisquares** [comment]
What have you tried so far?

**Comment by jakob3797** [comment]
ST doesn’t seem to work but 1 time it worked

**Comment by jakob3797** [comment]
I  tried lowering the conduct

**Comment by Tisquares** [comment]
What on earth is going on with your behaviors? Those should only be a 3x3 grid. Also, it is very difficult to read through your code when it's not formatted...

**Comment by jakob3797** [comment]
Actually it doesn’t have to be a 3x3 check the mod I made and test it

**Comment by jakob3797** [comment]
But the size is not the issue it is the behavior there is no behavior that is stain and st Is sticking for behaviors

**Comment by jakob3797** [comment]
> Actually it doesn’t have to be a 3x3 check the mod I made and test it

And the mod is lab.js

**Comment by jakob3797** [comment]
And I will give you how it should of come out formatted original 
elements.eunstainer_up2 = {
    behavior: behaviors.WALL,
  behaviorOn:   [
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25, 
  hardness: 1
};
 elements.eunstainer_up1 = {
    behavior: behaviors.WALL,
  behaviorOn:   [ 
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX"
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25,
  hardness: 1
};
elements.eunstainer_down2 = {
     behavior: behaviors.WALL,
     behaviorOn: [
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_down1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left2 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "ST:-1|ST:-1|XX|XX|XX",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "ST:-1|XX|XX",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_right2 = {
     behavior: behaviors.WALL,
  behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "XX|XX|XX|ST:-1|ST:-1",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
  hardness: 1,
};
elements.eunstainer_right1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|ST:-1",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     stain: -1,
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.unstain = {
    color: "#729fff",
    behavior: [
        "XX|XX|XX",
        "XX|XX|XX",
        "XX|XX|XX"
    ],
    stain: -1,
    tool: (pixel) => {
        doStaining({
            element: "unstain",
            x: pixel.x,
            y: pixel.y
        })
    },
    category: "tools",
    state: "solid",
};

**Comment by jakob3797** [comment]
elements.eunstainer_up2 = {
    behavior: behaviors.WALL,
  behaviorOn:   [
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25, 
  hardness: 1
};
 elements.eunstainer_up1 = {
    behavior: behaviors.WALL,
  behaviorOn:   [ 
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX"
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25,
  hardness: 1
};
elements.eunstainer_down2 = {
     behavior: behaviors.WALL,
     behaviorOn: [
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_down1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left2 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "ST:-1|ST:-1|XX|XX|XX",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "ST:-1|XX|XX",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_right2 = {
     behavior: behaviors.WALL,
  behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "XX|XX|XX|ST:-1|ST:-1",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
  hardness: 1,
};
elements.eunstainer_right1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|ST:-1",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     stain: -1,
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.unstain = {
    color: "#729fff",
    behavior: [
        "XX|XX|XX",
        "XX|XX|XX",
        "XX|XX|XX"
    ],
    stain: -1,
    tool: (pixel) => {
        doStaining({
            element: "unstain",
            x: pixel.x,
            y: pixel.y
        })
    },
    category: "tools",
    state: "solid",
};

``

**Comment by jakob3797** [comment]
> elements.eunstainer_up2 = {
    behavior: behaviors.WALL,
  behaviorOn:   [
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25, 
  hardness: 1
};
 elements.eunstainer_up1 = {
    behavior: behaviors.WALL,
  behaviorOn:   [ 
         "XX|ST:-1|XX",
         "XX|XX|XX",
         "XX|XX|XX"
    ],
    color: "#4103fc",
    category: "machines",
    conduct: 0.25,
  hardness: 1
};
elements.eunstainer_down2 = {
     behavior: behaviors.WALL,
     behaviorOn: [
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX",
         "XX|ST:-1|XX",
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_down1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|XX",
         "XX|ST:-1|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left2 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "ST:-1|ST:-1|XX|XX|XX",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_left1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "ST:-1|XX|XX",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.eunstainer_right2 = {
     behavior: behaviors.WALL,
  behaviorOn: [ 
         "XX|XX|XX|XX|XX",
         "XX|XX|XX|ST:-1|ST:-1",
         "XX|XX|XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
  hardness: 1,
};
elements.eunstainer_right1 = {
     behavior: behaviors.WALL,
     behaviorOn: [ 
         "XX|XX|XX",
         "XX|XX|ST:-1",
         "XX|XX|XX"
     ],
     color: "#4103fc", // Choose your desired color
     category: "machines",
     stain: -1,
     conduct: .25, // This defines how the element conducts electricity or energy, set as needed
     hardness: 1,
     state: "solid",
};
elements.unstain = {
    color: "#729fff",
    behavior: [
        "XX|XX|XX",
        "XX|XX|XX",
        "XX|XX|XX"
    ],
    stain: -1,
    tool: (pixel) => {
        doStaining({
            element: "unstain",
            x: pixel.x,
            y: pixel.y
        })
    },
    category: "tools",
    state: "solid",
};

**Comment by jakob3797** [comment]
It  doesn’t keep the tab or the way that it is supposed to be formed

**Comment by jakob3797** [comment]
![IMG_0199](https://github.com/R74nCom/sandboxels/assets/167775393/7efd2f13-076d-4d75-a53a-f12978e25bde)
![IMG_0200](https://github.com/R74nCom/sandboxels/assets/167775393/31eacb74-151f-4ee4-b018-b2d835264bd7)
![IMG_0201](https://github.com/R74nCom/sandboxels/assets/167775393/42edf858-b405-40b7-90d8-788f9678962b)

**Comment by DoobieRalsei** [comment]
I think the main issue is that you can’t put negative numbers into the ST property
