### ISSUE TITLE
Suggestion regarding the /mods directory

### ISSUE THREAD

**Issue by aduncan99** [R74nCom/sandboxels#728]
The /mods directory is kind of a mess (in my personal opinion).
You can see the names of all of the mods at a glance, but to figure out what it does, you have to open it up and look at the code.
It would be nice if there was a description file in there (e.g. /mods/descriptions.txt) where the names and description of the mods are listed, or if each mod had its own description file. This would help users who don't want to (or don't know how to) read the files.

IMPORTANT: I am not saying that everyone should go back and make a file describing their mod, (i will try to make description for them all if i have time), i just think that maybe we should try using description file(s) or something like that for any new mods from now on.

**Comment by voidapex11** [comment]
I would be willing to work on this and add descriptions to my mods. 

For all of my mods (2) I have added a new element to the mods section/category which runs an alert when its selected which archives a similar purpose. if  you want to see it, check out pullers.js

**Comment by slweeb** [comment]
There is already an organized list of mods with descriptions at mod-list.html (https://sandboxels.r74n.com/mod-list)

**Comment by winapiadmin** [comment]
> There is already an organized list of mods with descriptions at mod-list.html (https://sandboxels.r74n.com/mod-list)

but some mods and its elements are not described well (e.g. chess.js doesn't even have anything related, logicgates.js)
